name: BUILD
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  docs-GH:
    strategy:
      fail-fast: false
      matrix:
        pyversion: ["3.7", "3.8", "3.9", "3.10"]
    name: Build Docs on CPython ${{ matrix.pyversion }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.pyversion }}
    - name: Install Dependencies
      run: |
        poetry install
    - name: Build Docs
      run: poetry run sphinx-build -W ./doc/source .doc/build